GET http://localhost:8080/api/user

###

POST http://localhost:8080/api/user
content-type: application/json

{
    "nome": "Saulo",
    "email": "email@teste.com",
    "password": "123245"
}

###

PUT http://localhost:8080/api/user/1
content-type: application/json

{
    "nome": "Saulo Henrique",
    "email": "email@teste.com",
    "password": "123245"
}

###

DELETE http://localhost:8080/api/user/1